# Generated by Django 4.1.7 on 2023-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='usuario.png', upload_to=''),
        ),
    ]
